package com.edtech.qaservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Set;

@DynamoDBTable(tableName="AnswerService")
public class AnswerItem {
    private String id;
    private String author;
    private String answerTitle;
    private String createDate;
    private String answerText;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id;}
    public void setId(String id) {this.id = id;}

    @DynamoDBAttribute(attributeName = "author")
    public String getAuthor() { return author;}
    public void setAuthor(String author) {this.author = author;}

    @DynamoDBAttribute(attributeName = "createDate")
    public String getCreateDate() { return createDate;}
    public void setCreateDate(String createDate) {this.createDate = createDate;}

    @DynamoDBAttribute(attributeName="answerTitle")
    public String getAnswerTitle() { return answerTitle;}
    public void setAnswerTitle(String answerTitle) {this.answerTitle = answerTitle;}

    @DynamoDBAttribute(attributeName = "answerText")
    public String getAnswerText() { return answerText; }
    public void setAnswerText(String answerText) { this.answerText = answerText; }

    @Override
    public String toString() {
        return "Answer [id=" + id + ", answerTitle=" + answerTitle + ", createDate=" + createDate
                + ", answerText=" + answerText + ", author=" + author + "]";
    }
}
