package com.edtech.qaservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;

@DynamoDBDocument
public class AnswerItem {
    private String answerId;
    private String author;
    private String answerTimestamp;
    private String answerText;

    @DynamoDBAttribute(attributeName = "answerId")
    @DynamoDBAutoGeneratedKey
    public String getAnswerId() { return answerId;}
    public void setAnswerId(String answerId) {this.answerId = answerId;}

    @DynamoDBAttribute(attributeName = "author")
    public String getAuthor() { return author;}
    public void setAuthor(String author) {this.author = author;}

    @DynamoDBAttribute(attributeName = "answerTimestamp")
    public String getAnswerTimestamp() { return answerTimestamp;}
    public void setAnswerTimestamp(String answerTimestamp) {this.answerTimestamp = answerTimestamp;}

    @DynamoDBAttribute(attributeName = "answerText")
    public String getAnswerText() { return answerText; }
    public void setAnswerText(String answerText) { this.answerText = answerText; }

    @Override
    public String toString() {
        return "Answer [answerId=" + answerId + ", answerTimestamp=" + answerTimestamp
                + ", answerText=" + answerText + ", author=" + author + "]";
    }
}
