package com.edtech.qaservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
import java.util.Set;

@DynamoDBTable(tableName="QAService")
public class QuestionItem {
    private String questionId;
    private String author;
    private String questionTitle;
    private String questionTimestamp;
    private String questionText;
    private Set<String> questionTag;
    private List<AnswerItem> answers;

    @DynamoDBHashKey(attributeName = "questionId")
    @DynamoDBAutoGeneratedKey
    public String getQuestionId() { return questionId;}
    public void setQuestionId(String questionId) {this.questionId = questionId;}

    @DynamoDBAttribute(attributeName = "author")
    public String getAuthor() { return author;}
    public void setAuthor(String author) {this.author = author;}

    @DynamoDBAttribute(attributeName = "questionTimestamp")
    public String getQuestionTimestamp() { return questionTimestamp;}
    public void setQuestionTimestamp(String questionTimestamp) {this.questionTimestamp = questionTimestamp;}

    @DynamoDBAttribute(attributeName="questionTitle")
    public String getQuestionTitle() { return questionTitle;}
    public void setQuestionTitle(String questionTitle) {this.questionTitle = questionTitle;}

    @DynamoDBAttribute(attributeName = "questionText")
    public String getQuestionText() { return questionText; }
    public void setQuestionText(String questionText) { this.questionText = questionText; }

    @DynamoDBAttribute(attributeName = "questionTag")
    public Set<String> getQuestionTag() { return questionTag; }
    public void setQuestionTag(Set<String> questionTag) { this.questionTag = questionTag; }

    @DynamoDBAttribute(attributeName = "answers")
    @DynamoDBTypeConvertedJson
    public List<AnswerItem> getAnswers() { return answers; }
    public void setAnswers(List<AnswerItem> answers) { this.answers = answers; }

    @Override
    public String toString() {
        return "Question [questionId=" + questionId + ", questionTitle=" + questionTitle + ", questionTimestamp=" + questionTimestamp
                + ", questionText=" + questionText + ", author=" + author + ", questionTag=" + questionTag + ", answers=" + answers + "]";
    }
}
